site_name: Jenkins Containers
docs_dir: docs
# site_url/use_directory_urls were set as mkdocs 1.2.1 complained otherwise
site_url:
use_directory_urls: False
nav:
  - Home: index.md
  - Repo Layouts: layouts.md
  - Processes: processes.md
  - Build Philosophy: philosophy.md
theme:
    name: mkdocs
    nav_style: dark
extra_css:
    - css/extra.css
